### ISSUE TITLE
JAVA_HOME is not set

### ISSUE THREAD

**Issue by themnd** [smola/ansible-java-role#11]
When installing oracle java 7 the JAVA_HOME is not set.

I've used:

```
   - java_packages:
     - oracle-java7-installer
  roles:
    - { role: smola.java }
```

something like this would wonderful:

```
   - java_packages:
     - oracle-java7-installer
   - java_home_set: true
  roles:
    - { role: smola.java }
```
